### PR TITLE
Trying out a new style of readme

### PR DESCRIPTION
**Pull request by jsignell**
Loosely based on the pandas readme.

### CODE REVIEW

**Comment by jbednar** [comment]
Looks good!

image

But I'd vote for laying out the badges in each  labeled category left to right in a single row, rather than adding multiple rows.  

Also, "Latest dev release" is a bit misleading, as I think that shows the latest tag?  Maybe add a badge for pyviz/label/dev's current version, alongside the tag one, which would make it more accurate?

**Comment by jsignell** [comment]
image

**Comment by jsignell** [comment]
Any other things that would be helpful? The vision is that a person landing in a particular project will see these badges and we will be able to get a broad overview of the same information on the status-dashboard.

**Comment by jbednar** [comment]
Looks great, thanks so much!

**Pull request merged**
