### PR TITLE
:memo: Switch to protocol-relative URLs

### PR DESCRIPTION
**Pull request by rs2**
The docs should use `https://` where possible, but even better, default to the protocol of the current page.

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks for doing this @rs2. I'm happy for this to be merged.

**Comment by philippjfr** [comment]
Not sure what's up with the tests.

**Review by jbednar — COMMENTED** [review]
What are the advantages and disadvantages of this approach?  E.g. what happens when these files are viewed in a local clone of the repository -- won't they then (incorrectly) access the links as file:// links?

**Comment by jsignell** [comment]
I tested it out locally and it doesn't seem to work when previewing the file from an editor. I think being able to see the icons from an editor is a nice feature for the README, but maybe less important for the others.

**Comment by jbednar** [comment]
But it's not just the icons, right?  Won't *every* external link (to content outside this particular site) be broken locally, e.g. for everyone using our Jupyter notebooks?  That doesn't seem like an improvement.

**Comment by jsignell** [comment]
Yes that is true. Thanks for the suggestion though @rs2! It might be something that would be better incorporated into nbsite. And we do need to do a pass and make sure we are linking to the https versions of all available sites.

**Comment by jbednar** [comment]
Oh, that's a good point.  We could make the built website use protocol-relative URLs without changing the underlying source, essentially doing what this PR does but dynamically when building the site.  That would address my objections...

**Pull request closed without merging**
