### PR TITLE
Initial tutorial materials

### PR DESCRIPTION
**Pull request by philippjfr**
Added initial tutorial notebooks for training purposes. Adds the materials from JupyterCon as well as Network Graph and Streaming Data user guides from HoloViews.

### CODE REVIEW

**Comment by jbednar** [comment]
Looks good.  Please merge when you're ready.

**Comment by jbednar** [comment]
I assume you'll rename ``notebooks/15-Streaming_Data.ipynb`` and ``notebooks/Network_Graphs.ipynb``, but not yet because other nbs also need splitting/reordering?

**Comment by philippjfr** [comment]
Right, holding off on renaming until it's clear what the number and ordering will be.

**Comment by ceball** [comment]
Do any of these require large datasets?

**Comment by ceball** [comment]
Also, I see some test failures from missing dependencies (at least streamz), plus parambokeh not yet working with bokeh 0.12.10...

**Comment by philippjfr** [comment]
No, except for the NYC taxi data that's already in the datasets.yml. I do still have to add the smaller datasets that are needed though. I did forget about streamz, I'll add that shortly.

How far are we from parambokeh working with 0.12.10? We do want to cover it in the training next week.

**Comment by ceball** [comment]
Good news they don't need large datasets! We can delay dealing with that pain til later, then :)

I have a WIP PR in which at least some of parmabokeh works with 0.12.10, but not yet all of it works. I guess it's not a lot of work to get that finished.

**Comment by jbednar** [comment]
I'm way too hungry right now for you to be talking about parmabokeh!

**Comment by philippjfr** [comment]
Started running through the tutorials and am running into some issues:

* As we know parambokeh needs to be updated to support bokeh 0.12.10
* It seems there are some issues with datetimes, probably since matplotlib 2.1, may have to pin 2.0 for now.
* bokeh.sampledata.stocks has changed slightly requiring an update in 08-operations-and-pipelines

I can fix the other two but I'm not sure tests will pass without getting parambokeh working.

**Comment by philippjfr** [comment]
@ceball @jbednar As usual I can't get osx tests passing, this time due to cartopy errors. I'm going to disable them.

**Comment by philippjfr** [comment]
Tests now passing, merging.

**Pull request merged**
