### PR TITLE
Add Governance to the site

### PR DESCRIPTION
**Pull request by maximlt**
I thought it'd be a good idea to expose HoloViz's governance docs to the community.

image
image
image

### CODE REVIEW

**Comment by droumis** [comment]
There is currently a Governance section on the About page that links out.  I don't have a strong opinion about elevating Governance to its own nav tab, but the content should probably be merged so that it's in one place.

**Review by droumis — COMMENTED** [review]
There is currently a Governance section on the About page that links out. I don't have a strong opinion about elevating Governance to its own nav tab, but the content should probably be merged so that it's in one place. I'm a little bit concerned about the effect that adding more top-level pages has on the navigability of the website. But not concerned enough yet to block this. We can always reorganize/nest things later.

**Comment by maximlt** [comment]
Good catch, I didn't know there was a Governance section on the About page :)

> I'm a little bit concerned about the effect that adding more top-level pages has on the navigability of the website.

I'm not too concerned about that since they're all displayed in the side bar on the landing page. I hope one day the theme allows us to better configure how things get displayed in the nav bar.

**Comment by maximlt** [comment]
Done in https://github.com/holoviz/holoviz/pull/425

**Pull request closed without merging**
