### PR TITLE
Test the latest dev version of anaconda-project

### PR DESCRIPTION
**Pull request by maximlt**

### CODE REVIEW

**Comment by jlstevens** [comment]
Here is the error I see (in [this build failure at least](https://github.com/holoviz/holoviz/runs/7655416193?check_suite_focus=true#step:10:35)):

```
PackagesNotFoundError: The following packages are not available from current channels:

  - freetype==2.11.0=h70c0345_0
  - json5==0.9.6=pyhd3eb1b0_0
  - ld_impl_linux-64==2.38=h1181459_1
  - dbus==1.13.18=hb2f[20](https://github.com/holoviz/holoviz/runs/7655416193?check_suite_focus=true#step:10:21)db_0
  - libedit==3.1.20[21](https://github.com/holoviz/holoviz/runs/7655416193?check_suite_focus=true#step:10:22)0910=h7f8727e_0
  - gettext==0.21.0=hf68c758_0
  - backports==1.1=pyhd3eb1b0_0
  - libogg==1.3.5=h27cfd[23](https://github.com/holoviz/holoviz/runs/7655416193?check_suite_focus=true#step:10:24)_1
  - cryptography==37.0.1=py39h9ce1e76_0
  - nspr==4.33=h[29](https://github.com/holoviz/holoviz/runs/7655416193?check_suite_focus=true#step:10:30)5c915_0

Current channels:

  - https://conda.anaconda.org/pyviz/label/dev/linux-64
  - https://conda.anaconda.org/pyviz/label/dev/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  ```

The channels that make up `defaults` don't seem to be in that 'current channels list'. Any ideas @AlbertDeFusco ?

**Comment by hoxbro** [comment]
The anaconda-project.yml uses nodefaults, maybe we should remove and see if it works?

**Comment by maximlt** [comment]
Damned sure. Reading the discussion on `nodefaults` I have the feeling it was actually discarded by anaconda-project, until now. Let's see what happens when I remove it.

**Comment by jlstevens** [comment]
> Reading the discussion on nodefaults I have the feeling it was actually discarded by anaconda-project, until now. Let's see what happens when I remove it.

That is correct. I didn't realize `nodefaults` was in there!

**Comment by maximlt** [comment]
Sweet the CI went green!

(I'm sure I've added `nodefaults` to other projects...)

**Comment by jlstevens** [comment]
> (I'm sure I've added nodefaults to other projects...)

Yes, I've seen it around even though it apparently wasn't doing anything!

**Comment by maximlt** [comment]
Closing, as the intent of this PR was to test a dev release of anaconda-project.

**Pull request closed without merging**
