### PR TITLE
Various minor updates to material

### PR DESCRIPTION
**Pull request by philippjfr**
Made a start on updating the materials, main changes so far involve updating some GeoViews usage and using ``.options`` in a few more places.

### CODE REVIEW

**Review by jbednar — COMMENTED** [review]
ESRI is deprecated; use EsriImagery.

**Comment by jbednar** [comment]
Following https://github.com/pyviz/pyviz/issues/42 for to-do items.

**Comment by jbednar** [comment]
There are still some serious issues:

1. Zooming into 09_Operations_and_Pipelines seems unreliable; perhaps some streams are being shared inappropriately between cells? 
2. 11_Streaming_Data has a cell that aborts with a stacktrace: image
3. 12_Parameters_and_Widgets doesn't show any widgets: image
4. The plot doesn't refresh with the widgets or with zooming in 13_Deploying_Bokeh_Apps.

**Comment by jbednar** [comment]
Apart from the serious issues above, there are probably smaller issues, but I've at least now run all the notebooks and pushed fixes and updates as above.

**Comment by philippjfr** [comment]
>11_Streaming_Data has a cell that aborts with a stacktrace: 

Fixed by https://github.com/ioam/holoviews/pull/2863

**Comment by philippjfr** [comment]
>12_Parameters_and_Widgets doesn't show any widgets: 

Works for me. Are you using paramnb and parambokeh master? We really need those released.

**Comment by philippjfr** [comment]
>The plot doesn't refresh with the widgets or with zooming in 13_Deploying_Bokeh_Apps.

Had to come up with a temporary patch for parambokeh: https://github.com/ioam/parambokeh/pull/64

**Comment by philippjfr** [comment]
>Zooming into 09_Operations_and_Pipelines seems unreliable; perhaps some streams are being shared inappropriately between cells?

Could you elaborate, could not reproduce any issues.

**Comment by jbednar** [comment]
The versions I'm using are:

```
bokeh=0.13.0                   # /Users/jbednar/anaconda/envs/pyviz/lib/python3.6/site-packages/bokeh
holoviews=1.11.0a1.post3+g103daf5 # /Users/jbednar/holoviews_git/holoviews
hvplot=unknown                 # /Users/jbednar/hvplot/hvplot
geoviews=1.5.2                 # /Users/jbednar/geoviews/geoviews
datashader=0.6.7               # /Users/jbednar/anaconda/envs/pyviz/lib/python3.6/site-packages/datashader
param=1.7.0                    # /Users/jbednar/param/param
paramnb=2.0.2                  # /Users/jbednar/anaconda/envs/pyviz/lib/python3.6/site-packages/paramnb
parambokeh=0.2.2-9-gc4696cd    # /Users/jbednar/parambokeh/parambokeh
dask=0.18.1                    # /Users/jbednar/anaconda/envs/pyviz/lib/python3.6/site-packages/dask
streamz=0.3.0                  # /Users/jbednar/anaconda/envs/pyviz/lib/python3.6/site-packages/streamz
```

On the last cell of 09, I don't get datashader updates when zooming:
image

I also get strange behavior on the previous cell, where the range suddenly jumps as I'm zooming, though there could be some underlying stream changes that make this appropriate somehow:
image

Note that this is for "Run All"; you may not see issues if you run a cell at a time.

**Comment by philippjfr** [comment]
>On the last cell of 09, I don't get datashader updates when zooming:

You're not meant to, it's simply meant to illustrate the steps in the pipeline. The displayed object is not dynamic:

```
:Layout
   .RGB.Dynspread :RGB   [time,adj_close]   (R,G,B,A)
   .RGB.Datashade :RGB   [time,adj_close]   (R,G,B,A)
   .Curve.Rolling :Curve   [time]   (adj_close)
   .Curve.Price   :Curve   [time]   (adj_close)
```

>I also get strange behavior on the previous cell, where the range suddenly jumps as I'm zooming

I did see that once but can't consistently reproduce it. Probably won't have time to investigate this in any more detail, since you're probably skipping this section let's just file an issue and move on.

**Comment by philippjfr** [comment]
Once holoviews 1.10.7 and paramnb/parambokeh are released we should bump the versions in the environment and merge this. We can then follow up in another PR.

**Pull request merged**
