### PR TITLE
A number of minor tweaks

### PR DESCRIPTION
**Pull request by jlstevens**
In this PR I've made some minor tweaks and I will address the TODO items I listed in #42.

### CODE REVIEW

**Review by jbednar — APPROVED** [review]
Looks good. Ready to merge?

**Comment by jlstevens** [comment]
> Looks good. Ready to merge?

Nearly. One more tweak to introduce ``DynamicMap`` and I want to go through the last two exercises...then I'm done.

**Comment by jlstevens** [comment]
@jbednar If you agree that the last commit is correct, I think this is ready to merge.

**Comment by jbednar** [comment]
Looks good!  I'll merge in a bit.

**Pull request merged**
