### PR TITLE
Improve packaging and testing

### LINKED ISSUE #5: Replace test_notebooks with pytest-nbsmoke

### PR DESCRIPTION
**Pull request by ceball**
Closes #5, #63, #67, #68

Changes:
  * dependencies, pins, and package metadata specified once, in setup.cfg (doesn't have to stay as setup.cfg forever, but having one non-code config file is a start...)
  * removed conda recipe; instead generated from info in setup.cfg
  * the environment.yml file has been moved to examples and is generated from info in setup.cfg
  * test matrix (envs+commands) specified once in tox.ini (nobody likes that file, but at least it's all in one place...)
  * reorganized examples to be like rest of pyviz projects
  * simplified nbsite usage (nbsite handles assets, has slightly improved interface, supports ipynb for more things)
  * can generate pip package (but: current pyviz depends on unreleased things e.g. bokeh 1.0 for which there are no pip packages)
  * converted readme to md
  * removed test_examples script (use nbsmoke)
  * replaced custom user examples/data commands with those from pyct (note: alters the commands)
  * fixed apps to run from any current directory
  * pyviz.org can be updated by `website` tag (or by a release tag)

Additions:
  * weekly "follow tutorial instructions" job (i.e. test released packages) on win, mac, linux
  * weekly "try without pins" job (i.e. see what upcoming problems are on the horizon, although with luck they might have passed by the time it comes for a new release)
  * dev website at ioam-docs.github.io/pyviz-dev (updated by dev tag or by `website_dev` tag).

To do:
  * [x] update docs
  * [x] request to enable cron on appveyor account, then configure it
  * [x] release new pyctdev [edit: there's a dev release with the new features, which should be enough for now]
  * [x] check the apps on windows (particularly the data paths: can the original, simpler path form be used?) [edit: data paths nothing to do with windows; the more complex form is needed unless people always run the app from a specified directory]
  * [x] test the pytest exclude command works for user install

Just before merge:
  * [x] restore package upload steps
  * [x] restore build step conditions

### CODE REVIEW

**Comment by jbednar** [comment]
Looks great so far!  

Still can't quite tell if I prefer the apps/ to be under tutorial/ as I proposed before and as implemented here; I think maybe I prefer exercises/ to be under tutorial, but apps/ to be separate (examples/apps)?  @jlstevens and @philippjfr, any suggestions?  The reason to move apps/ out is that they are examples in their own right whether or not one is running the tutorial.  I'm actually wondering how we should handle apps in general; should an app have a corresponding notebook file that is the documentation for it on the website (in a separate section from the tutorial), here and on holoviews.org?

**Comment by jlstevens** [comment]
I don't yet have an opinion about your suggestions except for this one:

> I think maybe I prefer exercises/ to be under tutorial...

I agree that the exercises should be in the tutorial directory (people et confused as to where to find the exercises otherwise).

**Comment by philippjfr** [comment]
>The reason to move apps/ out is that they are examples in their own right whether or not one is running the tutorial.

I agree on moving polished apps out but isn't there at least one app that's part of an exercise?

>I'm actually wondering how we should handle apps in general; should an app have a corresponding notebook file that is the documentation for it on the website (in a separate section from the tutorial), here and on holoviews.org?

We probably should find some way. I think adding notebooks for apps will be confusing but there should be some way of generating a page for them which includes the code and a screenshot or gif.

**Comment by ceball** [comment]
If possible, would like some review of the following things...

## location of apps

`examples/tutorial/apps`: ok for now?

## modifications to apps

They are a bit uglier now: note the addition of `if __name__ == '__main__'`. That allows tools such as pytest to be able to inspect (presumably import...) these files without falling over on missing files or whatever. There is likely to be an alternative way, although it may require config for more than one tool. If the kind of change I've made is ok, I could probably clean up a bit and do a better job (I just stuck in the `if __main__` checks to get things to work).

See:
  * server_app.py: https://github.com/pyviz/pyviz/blob/0211b38896a0b5ddd9bcfdfadfdd21f1b62f624a/examples/tutorial/apps/server_app.py
  * osm-1billion.py:  https://github.com/pyviz/pyviz/blob/0211b38896a0b5ddd9bcfdfadfdd21f1b62f624a/examples/tutorial/apps/osm-1billion.py
  * nyc_taxi: https://github.com/pyviz/pyviz/blob/0211b38896a0b5ddd9bcfdfadfdd21f1b62f624a/examples/tutorial/apps/nyc_taxi/main.py
  * taxi_player: https://github.com/pyviz/pyviz/blob/a91d9a4ca6d5cfb21ffed23785e74454d62213f2/examples/tutorial/apps/taxi_player/main.py


## change to the example/data getting commands

Have switched to pyct, meaning:
  1. examples come from the package rather than being downloaded
  2. there's now one command to install examples and fetch data: `pyviz examples`
  3. the spelling of the separate commands to get the examples or get the data have changed: `pyviz --install-examples` is `pyviz copy-examples`; `pyviz --download-sample-data` is `pyviz fetch-data`. 
  4. won't overwrite existing examples (without `--force`)

**Comment by jbednar** [comment]
Thanks.  The location is fine, as are the changes to fetching data and examples.

The 'if main' checks don't seem fine.  Can't we make it not try to import files that are not in a module? These are scripts that are meant to be examples of how users should do things, and I don't think it's a good idea to force them to be importable, as I wouldn't recommend that a user do that.  I'd favor either never trying to import scripts (as who knows what that script is meant to do!), or specifically not trying to do these particular ones.

**Comment by ceball** [comment]
@jbednar, do the changes to the installation instructions seem ok? 

```
diff --git a/examples/tutorial/00_Setup.ipynb b/examples/tutorial/00_Setup.ipynb
index 0c49ae6..ad4a460 100644
--- a/examples/tutorial/00_Setup.ipynb
+++ b/examples/tutorial/00_Setup.ipynb
@@ -31,9 +31,8 @@
    "source": [
     "```\n",
     "! conda install -c pyviz pyviz\n",
-    "! pyviz --install-examples pyviz-tutorial\n",
-    "! pyviz --download-sample-data pyviz-tutorial/data\n",
-    "! cd pyviz-tutorial\n",
+    "! pyviz examples\n",
+    "! cd pyviz-examples/tutorial\n",
     "! jupyter notebook\n",
     "```"
    ]
@@ -44,8 +43,6 @@
    "source": [
     "See the full instructions at [pyviz.org](http://pyviz.org/installation.html) if you are on Windows or don't yet have conda. \n",
     "\n",
-    "Note: If you have previously installed the examples and want to save any of your own changes, rename your `pyviz-tutorial` directory before re-running the `--install-examples` command.\n",
-    "\n",
     "Once everything is installed, the following cell should print '1.11.0a4' or later:"
    ]
   },
```

```
diff --git a/doc/installation.rst b/doc/installation.rst
index d1028e8..5eee08b 100644
--- a/doc/installation.rst
+++ b/doc/installation.rst
@@ -29,31 +29,20 @@ Step 2: Install ``pyviz`` and other required libraries
    > conda install -c pyviz pyviz


-Step 3: Install the tutorials in your current working directory
----------------------------------------------------------------
+Step 3: Install the tutorials in your current working directory and download data
+---------------------------------------------------------------------------------

 ::

-   > pyviz --install-examples pyviz-tutorial
-   > cd pyviz-tutorial
+   > pyviz examples

-This will create a copy of the notebooks and related files needed for the tutorial in a new subdirectory ``pyviz-tutorial/``.
+This will (a) create a copy of the notebooks and related files needed for the tutorial in a new subdirectory ``pyviz-examples/tutorial``, and (b) download larger sample datasets such as NYC Taxi.

-Note: If you have previously installed the examples and want to keep
-any of your own changes, rename your existing ``pyviz-tutorial``
-directory before running the above command (which will overwrite any
-existing files).
+If you only want to get a copy of the examples, or only want to download the data, there are individual commands `pyviz copy-examples` and `pyviz fetch-data`; run e.g. `pyviz copy-examples --help` for more info.

-Step 4: Download the sample data
---------------------------------

-::
-
-   > pyviz --download-sample-data
-
-(Small datasets come with the examples, but large ones like the NYC Taxi dataset have to be downloaded separately, which can take some time.)
-
-Step 5: Launch Jupyter Notebook
+Step 4: Launch Jupyter Notebook
 -------------------------------

 You can then launch the notebook server and client::

+   > cd pyviz-examples/tutorial
    > jupyter notebook

@@ -65,11 +54,11 @@ A browser window with a Jupyter Notebook instance should now open, letting you s
 If you don't see the notebook appear (e.g. on some OS X versions), you may need to cut and paste the URL from the console output manually.


-Step 6: Test that everything is working
+Step 5: Test that everything is working
 ---------------------------------------

 You can see if everything has installed correctly by selecting the ``0 - Setup`` notebook from the index and doing "Cell/Run All" in the menus. There may be warnings on some platforms, but you'll know it is working if you see the orange HoloViews logo after it runs ``hv.extension()``.

-Step 7: Run the tutorials
+Step 6: Run the tutorials
 -------------------------
 Now you can run through the `tutorials <tutorial/index.html>`_, learn how to use all these tools, and apply them to anything you need to visualize.  Have fun!
```

The idea is supposed to be that the commands themselves tell you what to do (e.g. if you already have the examples, it won't overwrite and will tell you to move them away) or there's help available. But whether that's enough without further explanation in the docs, I'm not sure.

(Also not going to guarantee it all works perfectly, but we have chance to try it out before the next release/tutorial/conference. And it's the same commands across pyviz projects.)

**Comment by ceball** [comment]
>> [the apps] are a bit uglier now: note the addition of `if __name__ == '__main__'`
>> There is likely to be an alternative way, although it may require config for more than one tool.

> The 'if main' checks don't seem fine

Turned out to be not as bad as I remembered it would be: I only needed to tell pytest to ignore the apps directory.

**Comment by jbednar** [comment]
Those changes look good, thanks.  Matt R. suggested that we also remove the "!" from the suggested commands, as it was confusing people, and I agree.  I had put it there so that the cell would be executable within that notebook, but as most people would only need that information *before* they have notebooks running, as it's for setting up, most people probably see the website version of it and not the notebook version of it, and thus do not need the "!".

**Comment by ceball** [comment]
Thanks, the !s are covered in https://github.com/pyviz/pyviz/issues/97. I started trying to do it but had trouble with diffs, hence https://github.com/pyviz/pyviz/pull/99. I.e. will be dealt with separately from this PR.

**Comment by ceball** [comment]
I need to check something about the apps on windows, then pass through again for the TODOs, but after that I'll merge unless someone spots a problem and objects...

**Comment by ceball** [comment]
(Or I could give an in-person overview of the changes, if anyone wants that to understand what's going on in this PR before it gets merged...)

**Comment by jbednar** [comment]
Well, one problem is that it's not mergeable, but otherwise I'm happy to meet about it to let you show off your work if nothing else...

**Comment by ceball** [comment]
Not sure what you mean by not mergeable (apart from the things I mentioned above)?

**Comment by jbednar** [comment]
image

**Comment by jbednar** [comment]
I see now that it's squash-mergeable, though...

**Comment by ceball** [comment]
Are the apps supposed to be run from a specific directory? If so we should document that clearly (unless I missed it) and revert my changes (I changed them to find the data file relative to the app's source, rather than the current directory).

**Comment by philippjfr** [comment]
>Are the apps supposed to be run from a specific directory?

I think they were but not in any consistent or deliberate way. If your changes make this more consistent we should stick with it and document it.

**Comment by ceball** [comment]
I think in the future we could entirely overhaul example data loading in general, as we've discussed. But for now, at least notebooks always find data relative to themselves (doesn't matter where jupyter notebook launched from, unless I'm mistaken), and apps do the same.

**Comment by ceball** [comment]
There may be some bumps from merging this, so feel free to open issues to complain...

**Comment by philippjfr** [comment]
I think until there is a new doc build this PR has broken all the logos on the http://pyviz.org/ site.

**Comment by ceball** [comment]
Good point. The site should be updated soon; I just did `git tag -a website -m "Rebuild website because assets have moved."`

**Comment by ceball** [comment]
Actually, even after that builds, there'll be some other broken links. I didn't take account of some of the more recent changes that occurred after I originally opened my PR. Will fix up in a new PR.

**Comment by ceball** [comment]
pyviz.org should be ok now. Let me know if you find any problems.

**Pull request merged**
