### PR TITLE
Add HEPs to the website

### PR DESCRIPTION
**Pull request by maximlt**
HEPs were not exposed in the website, I'm suggesting they should be and this PR accomplishes that.

image
image
image

### CODE REVIEW

**Comment by droumis** [comment]
1. This should include something about who can submit HEPS and where. Can anyone make a HEP?
2. If anyone can make a HEP, does it require a core project member to sponsor a call for a vote? There should be some mention of HEP handling in the Governance. Could look at how [Conda governance](https://github.com/conda-incubator/governance#enhancement-proposal-approval) and others do it.
3. There should be a basic template or structure guide, similar to the CEPs of CFEPS, including author, link to discussion, etc.
4. Maybe pluralize the nav name to HEPs
5. I'm a little bit concerned about the effect that adding more top-level pages has on the navigability of the website. But not concerned enough yet to block this. We can always reorganize/nest things later.

**Review by droumis — COMMENTED** [review]
1. This should include something about who can submit HEPS and where. Can anyone make a HEP?
2. If anyone can make a HEP, does it require a core project member to sponsor a call for a vote? There should be some mention of HEP handling in the Governance. Could look at how [Conda governance](https://github.com/conda-incubator/governance#enhancement-proposal-approval) and others do it.
3. There should be a basic template or structure guide, similar to the CEPs of CFEPS, including author, link to discussion, etc.
4. Maybe pluralize the nav name to HEPs
5. I'm a little bit concerned about the effect that adding more top-level pages has on the navigability of the website. But not concerned enough yet to block this. We can always reorganize/nest things later.

**Comment by MarcSkovMadsen** [comment]
What is within the scope of a HEP?

If I wanted to suggest https://awesome-panel.github.io/holoviz-quarto/ associated with HoloViz similarly to PANEL-CHAT-EXAMPLES. Would that be a HEP?

**Comment by maximlt** [comment]
@droumis on 1/2/3, Numpy has https://numpy.org/neps/nep-0000.html for describing NEPs what you're asking for, Python has https://peps.python.org/pep-0001/. So I suggest adding HEP0 to fill that role. I don't plan to do this part of this PR though, so someone will have to decide whether it's a blocker or not. Personally, I'm motivated by a HEP I'm working on on Versioning and backwards compatibility, and I'd guess I'm entitled to submit a HEP.

> Maybe pluralize the nav name to HEPs

Done!

> I'm a little bit concerned about the effect that adding more top-level pages has on the navigability of the website. But not concerned enough yet to block this. We can always reorganize/nest things later.

Already replied in the other PR on exposing Governance :)

> If I wanted to suggest https://awesome-panel.github.io/holoviz-quarto/ associated with HoloViz similarly to PANEL-CHAT-EXAMPLES. Would that be a HEP?

Good question!

**Pull request closed without merging**
